import Header from "@/components/organisms/Header";
import "./globals.css";
import { Providers } from "./providers";
import Main from "@/components/organisms/Main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-poppins">
        <Providers>
          <Header />
          <Main>{children}</Main>
        </Providers>
      </body>
    </html>
  );
}
